### ISSUE TITLE
NoMethodError in settings

### ISSUE THREAD

**Issue by ashrafalzyoud** [sk-ys/redmine_enhanced_ux#6]
[dfaa64c0-390e-4e5e-8f1d-20414d3c6e01] NoMethodError (private method `api_request?' called for #<SettingsController:0x000000000411e0>):
[dfaa64c0-390e-4e5e-8f1d-20414d3c6e01]   
[dfaa64c0-390e-4e5e-8f1d-20414d3c6e01] lib/redmine/sudo_mode.rb:140:in `before'
[dfaa64c0-390e-4e5e-8f1d-20414d3c6e01] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
I, [2024-10-15T11:02:03.167618 #783544]  INFO -- : [bf3c5933-2e39-4073-adb3-b509267faa16] Started GET "/settings/plugin/redmine_enhanced_ux" for 10.55.10.203 at 2024-10-15 11:02:03 +0300

**Comment by sk-ys** [comment]
Hi, long time no see.
Thank you for your suggestions. Let me respond to each of your comments below:

1. This feature is currently not supported. I will consider it.
2. These themes are not supported. I will look into it.
3. Could you clarify what you have in mind? It would be helpful if you could provide an sketch of your idea.

Finally, please kindly be patient as I work on these.

**Comment by ashrafalzyoud** [comment]
3- when edit issue 
I note u put (project, tracker , parent is) in separate from another fields
It's be nice also put the another standard fields( Start day due date assigned . ..)
In another separate also

**Comment by sk-ys** [comment]
Do you have the following in mind?
![image](https://github.com/user-attachments/assets/f89bed9c-3cc8-4307-96b6-450fff8df5a4)

**Comment by ashrafalzyoud** [comment]
Yes same that in my mind
Perfect

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sk-ys** [comment]
@ashrafalzyoud 
Hi, I resolved issue 3 in the [dev](https://github.com/sk-ys/redmine_enhanced_ux/tree/dev) branch.
Please try it.
